### PR TITLE
Fix #4 Nonsensical Inputs Produce Sensical Results

### LINKED ISSUE #4: Bad error message with invalid input
Input:
```
@yamibot roll @index&zwnj;d@index
```

Expected output: Some user-friendly text about invalid dice. 

Actual Output:
```
An unexpected error `Cannot read property 'join' of undefined` occured and your commands could not be processed!
```

### PR DESCRIPTION
**Pull request by AccaliaDeElementia**

### CODE REVIEW

File: src/logiDice.js [hunk 1]
```diff
@@ -73,13 +73,16 @@ module.exports = {
 			return Promise.all(recPromises).then((subQueries) => {
 				let diceResult = subQueries.reduce((tally, current, index) => {
 					return mergeResults(tally, current);
-				}, false);
+				}, {
+					rolls: [],
```
Comment (yamikuronue) [inline src/logiDice.js]: This makes sense, but why not expand the sanity check on line 58? Maybe that needs to be removed now, since it'll behave differently if it wasn't for the 'd' and 'x' in 'index'?

File: test/unitTest.js [hunk 2]
```diff
@@ -39,11 +40,11 @@ describe('Logios Dice for SockBot', () => {
 
 		it('Should activate commands', () => {
 			sandbox.spy(fakeForum.Commands, 'add');
-			logiDice.plugin(fakeForum).activate().then(() => {
-				fakeForum.Commands.add.should.be.calledWith('roll');
-				fakeForum.Commands.add.should.be.calledWith('rollww');
-				fakeForum.Commands.add.should.be.calledWith('rollscion');
-				fakeForum.Commands.add.should.be.calledWith('rollfate');
+			return logiDice.plugin(fakeForum).activate().then(() => {
```
Comment (yamikuronue) [inline test/unitTest.js:43]: Good find! I mostly did TDD but I appear to have added the commands first :(

**Review by yamikuronue — COMMENTED** [review]
One outstanding question but the rest approved

File: src/logiDice.js (hunk 1 above)
Comment (AccaliaDeElementia) [reply src/logiDice.js]: I was trying for the minimum change required to produce "sensible" behavior given the degenerate input. in this case there was a dice roll attempt because the input was close enough to the expected format to pass, but not good enough.

I'm not against changing the sanity checks too to avoid hitting this fallback.

Ad for the difference for `x` .... whoopsies. please hold while i cover that case too.

Comment (AccaliaDeElementia) [reply src/logiDice.js]: oh....... the `x` case fails completely because it does a further regexp that only accepts `\d+d\d+` which the degenerate case does not include.

guard should be updated....

will work on that.

Comment (AccaliaDeElementia) [reply src/logiDice.js]: i couldn't figure out a good test for the initial guard that didn't break something else...... so now there's a new, more specific guard!
